<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sHrPhp%s'), '<span class="zf-green">', '</span>') ?></h1>    
    <p><?php echo sprintf($this->translate('We are Hampton Roads Php Group.  Check out our %smeetup%s or follow us on %stwitter%s!'), '<a href="http://www.meetup.com/Hampton-Roads-PHP-Meetup" target="_blank">', '</a>', '<a href="http://www.twitter.com/hrphpmeetup" target="_blank">', '</a>') ?></p>
    
</div>

<div class="row">

    

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Twitter Feed') ?></h3>
            </div>
            <div class="panel-body">
            <?php foreach($twitterFeed as $tweet) :?>
                <div><?php echo $tweet->text ?></div>
            <?php endforeach?>
            </div>
        </div>
    </div>
</div>
